//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LogProcessExceptions.rc
//
#define IDI_MODULE                      10
#define IDS_PROJNAME                    100
#define IDS_MAINWIZARD_CAPTION          1000
#define IDB_WIZARDWATERMARK             1011
#define IDB_WIZARDHEADER                1012
#define IDC_MAIN_OPERATION_OPENMINIDUMPFILEDIRECTORY 1512
#define IDC_MAIN_OPERATION_WRITEMINIDUMPNOW 1511
#define IDD_MAIN_INTRODUCTION           1100
#define IDC_WIZARDINTRODUCTION_TITLE    1110
#define IDC_WIZARDINTRODUCTION_SKIP     1111
#define IDC_WIZARDINTRODUCTION_DESCRIPTION 1112
#define IDD_MAIN_COMPLETION             1200
#define IDC_WIZARDCOMPLETION_ICON       1210
#define IDC_WIZARDCOMPLETION_TITLE      1211
#define IDC_WIZARDCOMPLETION_RESULT     1212
#define IDC_WIZARDCOMPLETION_FINISHLABEL 1213
#define IDD_MAIN_PROCESS                1300
#define IDC_MAIN_PROCESSES              1310
#define IDC_MAIN_REFRESHPROCESSES       1311
#define IDC_MAIN_DBGHELPVERSION         1312
#define IDD_MAIN_MINIDUMPTYPE           1400
#define IDC_MAIN_MINIDUMPTYPE_DATASEGMENTS 1410
#define IDC_MAIN_MINIDUMPTYPE_FULLMEMORY 1411
#define IDC_MAIN_MINIDUMPTYPE_HANDLEDATA 1412
#define IDC_MAIN_MINIDUMPTYPE_FILTERMEMORY 1413
#define IDC_MAIN_MINIDUMPTYPE_SCANMEMORY 1414
#define IDC_MAIN_MINIDUMPTYPE_UNLOADEDMODULES 1415
#define IDC_MAIN_MINIDUMPTYPE_INDIRECTLYREFERENCEDMEMORY 1416
#define IDC_MAIN_MINIDUMPTYPE_FILTERMODULEPATHS 1417
#define IDC_MAIN_MINIDUMPTYPE_PROCESSTHREADDATA 1418
#define IDC_MAIN_MINIDUMPTYPE_PRIVATEREADWRITEMEMORY 1419
#define IDC_MAIN_MINIDUMPTYPE_WITHOUTOPTIONALDATA 1420
#define IDC_MAIN_MINIDUMPTYPE_FULLMEMORYINFO 1421
#define IDC_MAIN_MINIDUMPTYPE_THREADINFO 1422
#define IDC_MAIN_MINIDUMPTYPE_CODESEGS  1423
#define IDC_MAIN_MINIDUMPTYPE_WITHOUTAUXILIARYSTATE 1424
#define IDC_MAIN_MINIDUMPTYPE_FULLAUXILIARYSTATE 1425
#define IDC_MAIN_MINIDUMPTYPE_PRIVATEWRITECOPYMEMORY 1426
#define IDC_MAIN_MINIDUMPTYPE_IGNOREINACCESSIBLEMEMORY 1427
#define IDC_MAIN_MINIDUMPTYPE_TOKENINFORMATION 1428
#define IDC_MAIN_MINIDUMPTYPE           1450
#define IDD_MAIN_OPERATION              1500
#define IDC_MAIN_OPERATION_LOG          1510
#define IDD_ABOUT                       29900
#define IDC_ABOUT_ICON                  29901
#define IDC_ABOUT_TITLE                 29902
#define IDC_ABOUT_PRODUCTVERSION        29903
#define IDC_ABOUT_FILEVERSION           29904
#define IDC_ABOUT_WEBSITETITLE          29905
#define IDC_ABOUT_WEBSITE               29906
#define IDC_ABOUT_EMAILTITLE            29907
#define IDC_ABOUT_EMAIL                 29908
#define IDC_ABOUT_COPYRIGHT             29909
#define IDC_ABOUT_COPYRIGHTWARNING      29910
#define IDC_ABOUT_LICENSE               29912

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
