////////////////////////////////////////////////////////////
// Copyright (C) Roman Ryltsov, 2008-2011
// Created by Roman Ryltsov roman@alax.info
// 
// $Id$

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(DD4E6DE7-AC06-4DB9-9439-83EFD8050F3B),
	version(1.0),
]
library AlaxInfoGpsLocationConverter
{
	importlib("stdole2.tlb");
};

