//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DirectShowSpy.rc
//
#define IDI_MODULE                      10
#define IDR_MODULE                      11
#define IDI_LISTVIEW_SUCCESS            70
#define IDI_LISTVIEW_FAILURE            71
#define IDS_PROJNAME                    100
#define IDR_FILTERGRAPHSPY              102
#define IDR_NOTHREADFILTERGRAPHSPY      103
#define IDR_FILTERMAPPERSPY             104
#define IDC_PROGRESS                    202
#define IDS_GRAPHBUILDERCALLBACK_GRAPH_PROPERTYSHEETCAPTION 1000
#define IDD_GRAPHBUILDERCALLBACK_GRAPH_PROPERTYPAGE 1100
#define IDC_GRAPHBUILDERCALLBACK_GRAPH_INTRODUCTION 1101
#define IDC_GRAPHBUILDERCALLBACK_GRAPH_SPLITTER 1102
#define IDC_GRAPHBUILDERCALLBACK_GRAPH_GRAPH 1103
#define IDC_GRAPHBUILDERCALLBACK_GRAPH_LOG 1104
#define IDC_GRAPHBUILDERCALLBACK_GRAPH_COPYTOCLIPBOARD 1105
#define IDC_GRAPHBUILDERCALLBACK_GRAPH_PROGRESS 1106
#define IDI_GRAPHBUILDERCALLBACK_LISTVIEW_ADDFILTER 1120
#define IDI_GRAPHBUILDERCALLBACK_LISTVIEW_REMOVEFILTER 1121
#define IDI_GRAPHBUILDERCALLBACK_LISTVIEW_SELECTEDFILTER 1122
#define IDI_GRAPHBUILDERCALLBACK_LISTVIEW_CREATEDFILTER 1123
#define IDD_ABOUT                       29900
#define IDC_ABOUT_ICON                  29901
#define IDC_ABOUT_TITLE                 29902
#define IDC_ABOUT_PRODUCTVERSION        29903
#define IDC_ABOUT_FILEVERSION           29904
#define IDC_ABOUT_WEBSITETITLE          29905
#define IDC_ABOUT_WEBSITE               29906
#define IDC_ABOUT_EMAILTITLE            29907
#define IDC_ABOUT_EMAIL                 29908
#define IDC_ABOUT_COPYRIGHT             29909
#define IDC_ABOUT_COPYRIGHTWARNING      29910

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        209
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         203
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
